#!/bin/sh

#---------- Variables ----------
#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

dot="${redColour}[${endColour}${yellowColour}*${endColour}${redColour}]${endColour}"

#---------- Functions ----------

function doneText(){
	echo -e "\n$dot ${blueColour}Done!${endColour}..."
}

# Banner
function banner(){
	clear
	echo "                                                                                      "
	echo -e "${redColour}   █████████                                                              "
	echo -e "${redColour}  ███░░░░░███                                                             "
	echo -e "${redColour} ░███    ░░░   ██████   ██████   ████████   ████████    ██████  ████████  "
	echo -e "${redColour} ░░█████████  ███░░███ ░░░░░███ ░░███░░███ ░░███░░███  ███░░███░░███░░███ "
	echo -e "${redColour}  ░░░░░░░░███░███ ░░░   ███████  ░███ ░███  ░███ ░███ ░███████  ░███ ░░░  "
	echo -e "${redColour}  ███    ░███░███  ███ ███░░███  ░███ ░███  ░███ ░███ ░███░░░   ░███      "
	echo -e "${redColour} ░░█████████ ░░██████ ░░████████ ████ █████ ████ █████░░██████  █████     "
	echo -e "${redColour}  ░░░░░░░░░   ░░░░░░   ░░░░░░░░ ░░░░ ░░░░░ ░░░░ ░░░░░  ░░░░░░  ░░░░░      ${purpleColour}by: ${yellowColour}@kyb3rvizsla @s4ori"
	echo "                                                                                      "

	echo -e "\n${yellowColour}Use:"
	echo -e "${grayColour}[${endColour}${yellowColour}*${endColour}${grayColour}]${endColour} ${greenColour}scanner ${turquoiseColour}<Mode> <IP>"

	echo -e "\n${yellowColour}Modes:"
	echo -e "$dot${purpleColour} -f ${blueColour}Fast"
	echo -e "$dot${purpleColour} -d ${blueColour}Detailed"
	echo -e "$dot${purpleColour} -a ${blueColour}Aggresive"
}

# fast
function fast(){
	nmap --min-rate 5000 -p- $fast -Pn -n -oN fastscan
	doneText
}

# detailed 
function detailed(){
	nmap --min-rate 5000 -p- $detailed -sCV -Pn -n -oN detailedscan
	doneText
}

# agresive
function agresive(){
	sudo nmap --min-rate 5000 -p- $steal -sCV -sS -Pn -n -oN hardscan -Pn 
	doneText
}

function opciones(){
	while getopts ":fdah:help" option;
	do
		case $option in
		f)
			state='1'
			fast
		;;
		d)
			detailed
		;;
		a)
			agresive
		;;
		h)
			banner
		;;
		help)
			banner
		;;
		*)
			echo -e "${redColour}R U Drunk?${endColour} ${yellowColour}that option does not exist,try with:${endColour} ${grayColour}scanner -help"
		;;
	esac
	done
}
#---------- Script ----------
# Main
state='0'

while getopts ":fdah:help" option;
do
	case $option in
	f)
		state='1'
		fast
	;;
	d)
		state='1'
		detailed
	;;
	a)
		state='1'
		agresive
	;;
	h)
		state='1'
		banner
	;;
	help)
		state='1'
		banner
	;;
	*)
		echo -e "${redColour}R U Drunk?${endColour} ${yellowColour}that option does not exist,try with:${endColour} ${grayColour}scanner -help"
	;;
esac
done

if [ $state = "0" ]; then
	banner;
else
	whoami > /dev/null
fi